# Generated by Django 4.2.7 on 2023-11-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0004_rename_userprofileinfo_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
