# Generated by Django 4.2.7 on 2023-11-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0005_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
