# Generated by Django 4.2.7 on 2023-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0007_alter_friend_friend_alter_friend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='temp_image.jpg', upload_to='profile_pics'),
        ),
    ]
