# Generated by Django 4.2.7 on 2023-11-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0010_userprofile_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
