# Generated by Django 4.2.7 on 2023-11-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_unfollow', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
