# Generated by Django 4.2.7 on 2023-11-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_share_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='share',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='share',
            name='shared_to',
        ),
    ]
