# Generated by Django 4.2.7 on 2023-12-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_cover_pic'),
        ('feed', '0003_remove_like_created_at_remove_share_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='userprofile.userprofile'),
            preserve_default=False,
        ),
    ]
